#!/bin/bash

export _JAVA_AWT_WM_NONREPARENTING=1

# Autostart

## Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

## Autokill
killall -9 ksuperkey xfce4-power-manager &
killall sxhkd; sxhkd &
killall dunst; dunst &

## Power Manager
xfce4-power-manager &

## Compositor
picom -b &

## Fix Cursor
xsetroot -cursor_name left_ptr &

## Bar
$HOME/.config/polybar/launch.sh &

# Bspwm configurations
bspc monitor -d 1 2 3 4 5 6 7 8
bspc config focus_follows_pointer false
bspc config top_padding 32
bspc config border_width 2
bspc config window_gap 0
bspc config focused_border_color "#98c379"
bspc config normal_border_color "#3e4452"
bspc config active_border_color "#e06c75"
bspc config presel_feedback_color "#56b6c2"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

# Window rules
bspc rule -r *:*
bspc rule -a Viewnior state=floating follow=on focus=on
bspc rule -a mpv state=floating follow=on focus=on
bspc -a feh state=floating
