#! /bin/sh

# Fix Java applications
export _JAVA_AWT_WM_NONREPARENTING=1


# Start applications from ~/.local/bin/autostart
$HOME/.local/bin/autostart &

# bspwm configuration
bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
