#!/usr/bin/env bash

path="/home/$USER/screenshots"
filename="$path/$(date).png" 

mkdir -p "$path"
maim --window $(xdotool getactivewindow) "$filename" && xclip -selection clipboard -t image/png "$filename"